	name: Build and Deploy
Â 	on: [push]
Â 	permissions:
Â 	contents: write
Â 	jobs:
Â 	build-and-deploy:
Â 	runs-on: ubuntu-latest
Â 	steps:
Â 	- name: Checkout ğŸ›ï¸
Â 	uses: actions/checkout@v4
Â 	Â 
Â 	- name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
Â 	run: |
Â 	npm ci
Â 	npm run build
Â 	Â 
Â 	- name: Deploy ğŸš€
Â 	uses: JamesIves/github-pages-deploy-action@v4
Â 	with:
Â 	folder: dist # The folder the action should deploy.